**Student Name: Nayanika Dubey <br>
Student ID: 2408008**

**Importing Numpy and Array Type.**

In [38]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



**Shape of an Array.**

In [39]:
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



**Reshaping an Array.**

In [40]:
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


**Arrays with evenly Spaced values - arange.**

In [41]:
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


**Arrays with evenly Spaced values - linspace.**

In [42]:
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


**Initializing an Array.**

In [43]:
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.5e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Converting list to array using np.array.**

In [44]:
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


**From shape of an existing array.**

In [45]:
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.94620201e-310 0.00000000e+000 1.18575755e-322]
 [3.95252517e-323 1.18575755e-322 3.95252517e-323]]


**Manipulatiing existing array.**

In [46]:
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np.copy(array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]

**With Concatenating Operation.**

In [47]:
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


**Introduction to ”ufuncs”.**

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


**Using 'np.dot'**

In [49]:
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


**Using "np.matmul”**

In [50]:
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


**Common linear algebra operation with np.linalg.**

In [51]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


**Exercise Questions:**

**Section 1:**

1. Initialize an empty array with size 2X2.




In [52]:
empty_array = np.empty((2, 2))
print(empty_array)

[[1. 2.]
 [3. 4.]]


2. Initialize an all one array with size 4X2.



In [53]:
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [54]:
full_array = np.full((3, 3), 7)
print(full_array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [55]:
arr = np.array([[1, 2], [3, 4]])
# Creating a zeros array with the same shape
zeros_like_array = np.zeros_like(arr)
print(zeros_like_array)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [56]:
arr = np.array([[1, 2], [3, 4]])
# Creating a zeros array with the same shape
zeros_like_array = np.zeros_like(arr)
print(zeros_like_array)


[[0 0]
 [0 0]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [57]:
given_list = [1, 2, 3, 4]
# Converting to numpy array
numpy_array = np.array(given_list)
print(numpy_array)


[1 2 3 4]


**Section 2:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.



In [58]:
array_range = np.arange(10, 50)
print(array_range)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [59]:
matrix = np.arange(9).reshape(3,3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [60]:
identity_matrix = np.ones((3,3))
print(identity_matrix)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [61]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)


0.4938195949203042


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [62]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print(min_value, max_value)

0.002070896921116394 0.9708763343747225


6. Create a zero array of size 10 and replace 5th element with 1.


In [63]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Replacing the 5th element
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [64]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print(reversed_array)


[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [65]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [66]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Section 3:**

**Problem 1:**
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?



In [67]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Addition
result = x + y
print(result)

# Subtraction
result = x - y
print(result)

# Multiplication
result = x * 2
print(result)

# Element-wise square
squared = x ** 2
print(squared)

# Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(dot_vw, dot_xv, dot_xy)

# Concatenate
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print(concat_xy, concat_vw)

#Attemping a concatenation for shape mismatch
#result = np.concatenate((x, v))

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
219 [29 77] [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]] [[ 9 10]
 [11 12]]


Problem 2:
For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB Transpose ̸= B transpose * A transpose.
3. Prove (AB) Transpose = B transpose * A Transpose

In [68]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

**Problem 3:**
Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [69]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

X = np.linalg.solve(A, B)
print(X)

A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)


[ 2.  1. -2.]
[ 2.  1. -2.]


**1. Element-wise Addition:**
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.


In [70]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure time for element-wise addition
start_time = time.time()
result_list = []
for i in range(1000000):
    result_list.append((list1[i]+list2[i]))
    end_time = time.time()

print("Time for list addition:", end_time - start_time)


Time for list addition: 0.7023539543151855


In [71]:
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()

print("Time for NumPy addition:", end_time - start_time)


Time for NumPy addition: 0.0025391578674316406


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.


In [72]:
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure time for element-wise multiplication
start_time = time.time()
for i in range(1000000):
  result_list.append((list1[i] * list2[i]))
end_time = time.time()

print("Time for list addition:", end_time - start_time)


Time for list addition: 0.3070499897003174


In [73]:
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_array = arr1 * arr2
end_time = time.time()

print("Time for NumPy multiplication:", end_time - start_time)

Time for NumPy multiplication: 0.0023381710052490234


**3. Dot Product**
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.


In [74]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure time for element-wise addition
start_time = time.time()
dot_product=0
for i in range(1000000):
  dot_product = dot_product + (list1[i] * list2[i])
end_time = time.time()

print("Time for list addition:", end_time - start_time)


Time for list addition: 0.28375697135925293


In [75]:
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
dot_product_array = np.dot(arr1, arr2)
end_time = time.time()

print("Time for NumPy dot product:", end_time - start_time)


Time for NumPy dot product: 0.0020508766174316406


**4. Matrix Multiplication**
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [76]:
matrix1 = [[j for j in range(1000)] for i in range(1000)]
matrix2 = [[j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result_matrix = [[0] * 1000 for i in range(1000)]

for i in range(len(matrix1)):  #rows
    for j in range(len(matrix2[0])):  #columns
        for k in range(len(matrix2)):  #rows
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()

print("Time for list matrix multiplication:", end_time - start_time)


Time for list matrix multiplication: 515.4498915672302


In [77]:
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))

# Measure time for matrix multiplication
start_time = time.time()
result_matrix = np.dot(matrix1, matrix2)
end_time = time.time()

print("Time for NumPy matrix multiplication:", end_time - start_time)


Time for NumPy matrix multiplication: 0.062085866928100586
